### ISSUE TITLE
App Switcher, apps background

### ISSUE THREAD

**Issue by hossammourad** [mjsolidarios/unity-flatify-icons#1]
The background cube is gone from the unity launcher but they're also gone from the App Switcher (ALT + TAB).

**Comment by ghost** [comment]
But this is good :) We have underline + text in it's place. It's easier to tell which is the selected application.

**Comment by shas0408** [comment]
Follow these instructions to get back the Window Switcher.
You'll need to install **CompizConfig Settings Manager** to enable it.
- Install by using: `sudo apt-get install compizconfig-settings-manager`
- Search for **CompizConfig Settings Manager** in Unity Dash.
- Look for Window Management and put a check-mark on  Application Switcher.

**Note:** CCSM is powerful tool and should be used very carefully. Before changing anything else, make sure you know what you are doing. Configuring incompatible plugins may even render your desktop useless. As an added step, you may remove the package after configuring this setting. Use `sudo apt-get purge compizconfig-settings-manager` to remove the CCSM.
